### Этот файл автоматически перезаписывается порталом при создании,
### удалении или изменении настроек станции. Не редактируйте вручную.

stations = [
  {id="93b23086bdb8", slug="rock", media_dir="/mediateka/radio/rock", mode="random", bitrate=256, mount="rock"},
  {id="8473cbf385f9", slug="fmcafe", media_dir="/mediateka/radio/fmcafe", mode="random", bitrate=256, mount="fmcafe"},
  {id="f5d91701efa8", slug="testovaya", media_dir="/mediateka/radio/testovaya", mode="random", bitrate=128, mount="test"},
  {id="aeab2170583e", slug="elektroshok", media_dir="/mediateka/radio/elektroshok", mode="random", bitrate=256, mount="elecktoshock"},
  {id="b8ba7b02558d", slug="elektroshok-2010-2013", media_dir="/mediateka/radio/elektroshok-2010-2013", mode="random", bitrate=128, mount="electroshock2"},
  {id="b60f5e19f856", slug="bigpodcast", media_dir="/mediateka/radio/bigpodcast", mode="normal", bitrate=192, mount="bigpodcast"},
  {id="ef6cb43e4dc6", slug="essentialmix", media_dir="/mediateka/radio/essentialmix", mode="random", bitrate=256, mount="essentialmix"},
  {id="3c955a147287", slug="inoveschanie", media_dir="/mediateka/radio/inoveschanie", mode="random", bitrate=192, mount="inoveshanie"},
  {id="d48f84ab2a04", slug="the-alligator-hour-with-joshua-homme", media_dir="/mediateka/radio/the-alligator-hour-with-joshua-homme", mode="random", bitrate=256, mount="alligatorhour"},
  {id="51791f60cb53", slug="ebanko-fm", media_dir="/mediateka/radio/ebanko-fm", mode="random", bitrate=192, mount="ebankofm"},
  {id="a29ea8e7455d", slug="dj-kirillof-mixer", media_dir="/mediateka/radio/dj-kirillof-mixer", mode="random", bitrate=256, mount="mixer"},
  {id="c08c3beb9931", slug="bachinskiy-i-stillavin", media_dir="/mediateka/radio/bachinskiy-i-stillavin", mode="random", bitrate=192, mount="bach&stil"},
  {id="9e45513f5771", slug="ultra", media_dir="/mediateka/radio/ultra", mode="random", bitrate=128, mount="ultra"},
  {id="93309e55864d", slug="stoner", media_dir="/mediateka/radio/stoner", mode="random", bitrate=256, mount="stone"},
  {id="bd7d8b7db7a1", slug="evgenika", media_dir="/mediateka/radio/evgenika", mode="random", bitrate=256, mount="evgenika"}
]
